### ISSUE TITLE
Animation bug

### ISSUE THREAD

**Issue by michaeldavidtodd** [aboutjax/framer-flip-card-module#4]
I haven't been able to figure out why this is happening, but it's within the Framer preview panel and Safari. Chrome renders correctly. I was seeing this same issue in a prototype I was building myself. For some reason, this example works perfectly, though: http://codepen.io/akolchenko/pen/vJdtx

![2d678574-1446-48ed-81e3-065226d8dbcb-1940-0000145f8383c443](https://cloud.githubusercontent.com/assets/1836000/14149627/0fe5dec6-f673-11e5-9015-8043d62082b3.gif)

**Comment by SamuelBarbosa** [comment]
I don’t know if this is background bug or new version of Framer bug but i have the same problem. I have made a video to explain it: https://up.kibakoapp.com/obTRQpYNKx 
Also i have reported it on the Framer Facebook Group:
https://www.facebook.com/groups/framerjs/permalink/842800075847065/

**Comment by michaeldavidtodd** [comment]
Interesting…
